version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: ./server
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - 80:80

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes: 
 data: {}